db_file: "bot.db"

bot_url: "https://t.me/Save_the_information_bot"

messages:
  responses:
    start: "Hello! Please, for correctly working, authorize here: %s"
    already_authorized: "You already authorized. Send me the link and i save her"
    saved_successfully: "The link is successfully saved"
    unknown_command: "Invalid command"
  errors:
    default: "An unknown error has occurred"
    invalid_url: "Invalid link"
    unauthorized: "You are not authorized. Use /start"
    unable_to_save: "Sorry... Cant save the link. Try again later :)"